### ISSUE TITLE
Error Message String Contains [object Object]

### ISSUE THREAD

**Issue by svozza** [sanctuary-js/sanctuary-def#102]
I'm currently working on the PR generated by https://github.com/sanctuary-js/sanctuary/issues/291. The new implementation of `pluck` looks like this:

```js
def('pluck',
      {a: [Accessible]},
      [$.String, $.Array({a: [Accessible]}), $.Array(a)],
      pluck);
```

Unfortunately it seems that `sanctuary-def` can't handle `$.Array({a: [Accessible]})`:

```
TypeError: Invalid value

pluck :: Accessible a => String -> Array [object Object] -> Array a
                         ^^^^^^
                           1
```

**Comment by davidchambers** [comment]
`$.Array({a: [Accessible]})` is not a valid type. `$.Array` expects a `Type` value as an argument. You'll need something like this:

```javascript
def('pluck', {a: [Accessible]}, [$.String, $.Array(a), $.Array(b)], pluck);
```

I'd like `$.Array` (and other type constructors) to assert that the given arguments are in fact `Type` values. I'll investigate this.

(Keep in mind that `Accessible` is a `TypeClass` value rather than a `Type` value.)

**Comment by svozza** [comment]
Yeah, I thought it looked odd when I wrote the type out but I figured because I didn't get an error that it was OK.

**Comment by davidchambers** [comment]
> I'd like `$.Array` (and other type constructors) to assert that the given arguments are in fact `Type` values. I'll investigate this.

Let's provide helpful feedback in such cases.
