### ISSUE TITLE
Improve error message when no matching type is found

### ISSUE THREAD

**Issue by panayi** [sanctuary-js/sanctuary-def#144]
#### Illustrative example

```javascript
S.get(S.is(Object), 'input', this.refs)
```

fails with:

```
Uncaught TypeError: Type-variable constraint violation

get :: Accessible a => (b -> Boolean) -> String -> a -> Maybe c
                        ^
                        1

1)  [object HTMLInputElement] ::

Since there is no type of which all the above values are members,
the type-variable constraint has been violated.
```

The empty right of `::` shows that no matching type has been found. However it can be hard to figure this out, especially for Sanctuary beginners. The error message could explicitly state that no matching error has been found, and make it easier to infer that a new type definition is needed.

Related Gitter discussion: https://gitter.im/sanctuary-js/sanctuary?at=5905aa848e4b63533d1a3f15

**Comment by davidchambers** [comment]
Thank you for taking the time to open this issue, @panayi, and for presenting the problem so clearly.

From seeing lots of sanctuary-def error messages one learns that there are usually types listed to the right of the `::`, but if there are no types listed in one's *first* encounter with these error messages one won't appreciate the significance of the nothingness to the right of the `::`.

The question is what should appear to the right of the `::` when there are no types to present. Currently the type representations are separated by `, ` to limit syntactic noise. The lack of wrapping `{ ... }` or `[ ... ]` means the empty set is invisible rather than `{ }` or `[ ]`. Brackets would make the empty set clearer, but `[ Number ]` could be misinterpreted as `Array Number`. This suggests the right approach is to display something special when there are no types. Something like this, perhaps:

```
1)  [object HTMLInputElement] :: (no types)
```

What do you suggest, @panayi?

**Comment by panayi** [comment]
@davidchambers thanks for the explanation. `(no types)` sounds great. Some less succinct suggestions:

- `(no known types in env)`
- `(unknown types)`
- `(undetermined types)`

----
Also:

```
Since there is no type of which all the above values are members...
```

Although this is true in this case, I think there _may_ be a type for which all the above values are members. However that type (if it exists) is unknown.  So perhaps it could say:

```
Since there is no known type of which all the above values are members...
```
