### ISSUE TITLE
Comparison to Typescript?

### ISSUE THREAD

**Issue by lolcookie** [sanctuary-js/sanctuary-def#176]
Both allow for construction of types (interfaces in typescript) and type checking.

What advantages does sanctuary-def offer over typescript?

**Comment by davidchambers** [comment]
sanctuary-def is more expressive in two ways. First, because types are defined via predicates (functions of type `a -> Boolean`) one can define types which are more granular than the “types” JavaScript provides. For example, rather than just having a Number type, we can define Number, FiniteNumber, Integer, NonZeroInteger, PositiveInteger, and so on.

Secondly, we can use parameterized type variables. TypeScript permits the use of “nullary” type variables in signatures such as `(a -> b) -> Array a -> Array b` but it does allow us to parameterize `Array` to arrive at the maximally polymorphic `Functor f => (a -> b) -> f a -> f b`. This limitation makes writing type definitions for polymorphic functions such as [`S.map`][1] an onerous task, as one is forced to enumerate all the types in the environment which satisfy the `Functor f` constraint.

The extent to which TypeScript's (intentional) limitations will be frustrating depends on the amount of polymorphic code in one's project. If the vast majority of one's code deals with concrete types such as Number, String, and record types, TypeScript will feel quite capable.

The main advantage of TypeScript is that checks are performed at compile time rather than at run time. sanctuary-def's type checking can significantly affect performance, so it's advisable to disable it in production. On the other hand, TypeScript's straightforward left-to-right algorithm for resolving type variables can result in type variables resolving to `Any`, allowing some invalid programs to pass type checking. In theory, at least, sanctuary-def never suppresses a type error (if type checking is enabled).


[1]: https://sanctuary.js.org/#map

**Comment by lolcookie** [comment]
Great response, thank you.

**Comment by davidchambers** [comment]
You're welcome, @lolcookie. :)
