### ISSUE TITLE
Module type should be added to default env

### ISSUE THREAD

**Issue by mfidemraizer** [sanctuary-js/sanctuary-def#218]
When a module is imported using dynamic imports (i.e. `import(...)` / `import :: String -> Promise Module`), the returned value is `Module` which is like an object.

Since dynamic imports will be used more and more, I consider that `sanctuary-def` should include `Module` type as part of its default `env`.

**Comment by davidchambers** [comment]
Could you propose a predicate function, @mfidemraizer?

**Comment by davidchambers** [comment]
Cool. Feel free to submit a pull request. :)

**Comment by mfidemraizer** [comment]
Yeah, in fact I resolved this in my own code just like @Avaq has proposed.

**Comment by mfidemraizer** [comment]
Oh and I tried to find another approach but it seems like `toString` is the unique approach to identify `Module` type: https://stackoverflow.com/questions/51466299/match-object-of-type-module

**Comment by Avaq** [comment]
You can do `toString.call(module) === '[object Module]'`, or `module && module[Symbol.toStringTag] === 'Module'`.

**Comment by loganfsmyth** [comment]
I want to clarify that the `Module` object is just a generic language thing, it is not specific to dynamic import. It's the same object that you get by using a namespace import .e.g

    import * as things from "foo";

Also it may not matter in your case, since I'm not familiar with this project, but JS bundlers do not polyfill the `[object Module]` `toString` behavior as far as I know.

**Comment by mfidemraizer** [comment]
@loganfsmyth This corner case is really challenging because `sanctuary-def` should type check it like a literal object but this would cause every object to type check too...
